"""funnel pdf retry sheet merge reschedule flag

Additive only (qa-review follow-up to 74ce2ab64d21):
  funnel_entries.pdf_attempts / pdf_retry_at — PDF send retry with backoff
  funnel_entries.sheet_merged_id — merged Instagram entry whose sheet row is
      taken over or marked "Birlashtirildi"
  interview_bookings.rescheduled — cancelled by a reschedule (not counted as a
      cancellation in stats)
Data: seeded sales messages that still contain "[raqam]"/"[imtiyoz" are switched
off (the sender skips them anyway; the panel should show them as inactive).

Revision ID: 087311873265
Revises: 74ce2ab64d21
Create Date: 2026-09-25 21:01:57.649469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087311873265'
down_revision: Union[str, Sequence[str], None] = '74ce2ab64d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funnel_entries', sa.Column('pdf_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('funnel_entries', sa.Column('pdf_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('funnel_entries', sa.Column('sheet_merged_id', sa.Uuid(), nullable=True))
    op.add_column('interview_bookings', sa.Column('rescheduled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###
    op.execute("UPDATE funnel_messages SET is_active = false "
               "WHERE text LIKE '%[raqam%' OR text LIKE '%[imtiyoz%'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_bookings', 'rescheduled')
    op.drop_column('funnel_entries', 'sheet_merged_id')
    op.drop_column('funnel_entries', 'pdf_retry_at')
    op.drop_column('funnel_entries', 'pdf_attempts')
    # ### end Alembic commands ###
