"""lead magnet funnel

Adds the lead-magnet funnel tables (SPEC §10.2): funnel_entries, funnel_messages,
funnel_deliveries, funnel_files, interview_bookings. Only new tables — existing
tables are not touched. Seeds three placeholder sales messages (10 min, 1 day,
2 days after the PDF), switched OFF: "[raqam]" parts are for the client to fill
in the panel before activating them (the sender also skips unfilled texts).

Revision ID: 74ce2ab64d21
Revises: 0dd1fc0742c5
Create Date: 2026-09-25 20:19:10.233044

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ce2ab64d21'
down_revision: Union[str, Sequence[str], None] = '0dd1fc0742c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Frozen copy (migrations must not import app code). Placeholders: [raqam], [imtiyoz].
_SALES_MESSAGES = (
    (10, "Qo'llanma yoqdimi? 😊\n\n"
         "Wunderkind maktabida har bir bola — kichik lider. Sinflarimizda atigi [raqam] nafar "
         "o'quvchi, har kuni ingliz tili va mantiqiy fikrlash darslari, [raqam] yillik "
         "tajribaga ega ustozlar.\n\n"
         "Yangi o'quvchilar qabuli davom etmoqda. Farzandingiz bilan bepul tanishuv "
         "suhbatiga yoziling — qulay vaqtni hoziroq tanlashingiz mumkin 👇"),
    (60 * 24, "Nega ota-onalar farzandini Wunderkind'ga ishonib topshirishadi? 🌟\n\n"
              "✅ Sinfda [raqam] nafargacha o'quvchi — har bir bolaga alohida e'tibor\n"
              "✅ Bitiruvchilarimizning [raqam]% i nufuzli maktab va litseylarga o'qishga "
              "kirgan\n"
              "✅ Kun tartibi, sog'lom ovqatlanish va to'garaklar — hammasi bir joyda\n\n"
              "Tanishuv suhbatida farzandingizning qiziqishlari va kuchli tomonlarini birga "
              "aniqlaymiz. Suhbat bepul va Sizni hech narsaga majburlamaydi 😊"),
    (60 * 24 * 2, "Joylar soni cheklangan ⏳\n\n"
                  "Shu hafta suhbatga yozilgan oilalar uchun: [imtiyoz — masalan, birinchi oy "
                  "uchun [raqam]% chegirma].\n\n"
                  "Farzandingiz kelajagiga eng yaxshi sarmoya — to'g'ri muhit va mehribon "
                  "ustozlar. Qulay kun va vaqtni tanlang, qolganini o'zimiz tashkil qilamiz 👇"),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funnel_files',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('tg_file_id', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('funnel_messages',
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('image_content_type', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_messages_created_at'), 'funnel_messages', ['created_at'], unique=False)
    op.create_table('funnel_entries',
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('start_token', sa.String(length=24), nullable=False),
    sa.Column('ig_user_id', sa.String(length=64), nullable=True),
    sa.Column('ig_username', sa.String(length=120), nullable=True),
    sa.Column('ig_comment_id', sa.String(length=64), nullable=True),
    sa.Column('follow_checks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tg_user_id', sa.String(length=32), nullable=True),
    sa.Column('tg_chat_id', sa.String(length=32), nullable=True),
    sa.Column('tg_username', sa.String(length=120), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('step', sa.String(length=24), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('followed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('link_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bot_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opted_out', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sheet_row', sa.Integer(), nullable=True),
    sa.Column('sheet_dirty', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_token'),
    sa.UniqueConstraint('tg_user_id')
    )
    op.create_index(op.f('ix_funnel_entries_created_at'), 'funnel_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_funnel_entries_ig_user_id'), 'funnel_entries', ['ig_user_id'], unique=False)
    op.create_index(op.f('ix_funnel_entries_lead_id'), 'funnel_entries', ['lead_id'], unique=False)
    op.create_index(op.f('ix_funnel_entries_pdf_sent_at'), 'funnel_entries', ['pdf_sent_at'], unique=False)
    op.create_index(op.f('ix_funnel_entries_sheet_dirty'), 'funnel_entries', ['sheet_dirty'], unique=False)
    op.create_index(op.f('ix_funnel_entries_source'), 'funnel_entries', ['source'], unique=False)
    op.create_index(op.f('ix_funnel_entries_step'), 'funnel_entries', ['step'], unique=False)
    op.create_table('funnel_deliveries',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['funnel_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['funnel_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'message_id', name='uq_funnel_deliveries_entry_message')
    )
    op.create_index(op.f('ix_funnel_deliveries_message_id'), 'funnel_deliveries', ['message_id'], unique=False)
    op.create_table('interview_bookings',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['funnel_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_bookings_created_at'), 'interview_bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_interview_bookings_entry_id'), 'interview_bookings', ['entry_id'], unique=False)
    op.create_index(op.f('ix_interview_bookings_starts_at'), 'interview_bookings', ['starts_at'], unique=False)
    op.create_index(op.f('ix_interview_bookings_status'), 'interview_bookings', ['status'], unique=False)
    op.create_index('uq_interview_bookings_one_scheduled', 'interview_bookings', ['entry_id'], unique=True, postgresql_where=sa.text("status = 'scheduled'"), sqlite_where=sa.text("status = 'scheduled'"))
    # ### end Alembic commands ###

    messages = sa.table(
        "funnel_messages",
        sa.column("id", sa.Uuid()), sa.column("sort_order", sa.Integer()),
        sa.column("text", sa.Text()), sa.column("delay_minutes", sa.Integer()),
        sa.column("is_active", sa.Boolean()),
    )
    op.bulk_insert(messages, [
        {"id": uuid.uuid4(), "sort_order": order, "text": text, "delay_minutes": delay,
         "is_active": False}
        for order, (delay, text) in enumerate(_SALES_MESSAGES)
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_interview_bookings_one_scheduled', table_name='interview_bookings', postgresql_where=sa.text("status = 'scheduled'"), sqlite_where=sa.text("status = 'scheduled'"))
    op.drop_index(op.f('ix_interview_bookings_status'), table_name='interview_bookings')
    op.drop_index(op.f('ix_interview_bookings_starts_at'), table_name='interview_bookings')
    op.drop_index(op.f('ix_interview_bookings_entry_id'), table_name='interview_bookings')
    op.drop_index(op.f('ix_interview_bookings_created_at'), table_name='interview_bookings')
    op.drop_table('interview_bookings')
    op.drop_index(op.f('ix_funnel_deliveries_message_id'), table_name='funnel_deliveries')
    op.drop_table('funnel_deliveries')
    op.drop_index(op.f('ix_funnel_entries_step'), table_name='funnel_entries')
    op.drop_index(op.f('ix_funnel_entries_source'), table_name='funnel_entries')
    op.drop_index(op.f('ix_funnel_entries_sheet_dirty'), table_name='funnel_entries')
    op.drop_index(op.f('ix_funnel_entries_pdf_sent_at'), table_name='funnel_entries')
    op.drop_index(op.f('ix_funnel_entries_lead_id'), table_name='funnel_entries')
    op.drop_index(op.f('ix_funnel_entries_ig_user_id'), table_name='funnel_entries')
    op.drop_index(op.f('ix_funnel_entries_created_at'), table_name='funnel_entries')
    op.drop_table('funnel_entries')
    op.drop_index(op.f('ix_funnel_messages_created_at'), table_name='funnel_messages')
    op.drop_table('funnel_messages')
    op.drop_table('funnel_files')
    # ### end Alembic commands ###
