"""funnel message buttons

Additive only (SPEC §14): buttons under sales messages, the first click of each
entry per button, and on funnel_messages the booking-button switch plus the
click condition (none / clicked / not_clicked of another message). Existing
messages keep condition "none" and the booking button → behave as before.

Revision ID: b597d8612c25
Revises: 09e5f6abd1dc
Create Date: 2026-09-26 21:02:46.372829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b597d8612c25'
down_revision: Union[str, Sequence[str], None] = '09e5f6abd1dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funnel_message_buttons',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['funnel_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_message_buttons_created_at'), 'funnel_message_buttons', ['created_at'], unique=False)
    op.create_index(op.f('ix_funnel_message_buttons_message_id'), 'funnel_message_buttons', ['message_id'], unique=False)
    op.create_table('funnel_button_clicks',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('button_id', sa.Uuid(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['button_id'], ['funnel_message_buttons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entry_id'], ['funnel_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['funnel_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'button_id', name='uq_funnel_button_clicks_entry_button')
    )
    op.create_index(op.f('ix_funnel_button_clicks_button_id'), 'funnel_button_clicks', ['button_id'], unique=False)
    op.create_index(op.f('ix_funnel_button_clicks_message_id'), 'funnel_button_clicks', ['message_id'], unique=False)
    op.add_column('funnel_messages', sa.Column('show_book_button', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('funnel_messages', sa.Column('condition', sa.String(length=16), server_default='none', nullable=False))
    op.add_column('funnel_messages', sa.Column('condition_message_id', sa.Uuid(), nullable=True))
    op.add_column('funnel_messages', sa.Column('condition_button_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_funnel_messages_condition_message_id', 'funnel_messages', 'funnel_messages', ['condition_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_funnel_messages_condition_message_id', 'funnel_messages',
                       type_='foreignkey')
    op.drop_column('funnel_messages', 'condition_button_id')
    op.drop_column('funnel_messages', 'condition_message_id')
    op.drop_column('funnel_messages', 'condition')
    op.drop_column('funnel_messages', 'show_book_button')
    op.drop_index(op.f('ix_funnel_button_clicks_message_id'), table_name='funnel_button_clicks')
    op.drop_index(op.f('ix_funnel_button_clicks_button_id'), table_name='funnel_button_clicks')
    op.drop_table('funnel_button_clicks')
    op.drop_index(op.f('ix_funnel_message_buttons_message_id'), table_name='funnel_message_buttons')
    op.drop_index(op.f('ix_funnel_message_buttons_created_at'), table_name='funnel_message_buttons')
    op.drop_table('funnel_message_buttons')
    # ### end Alembic commands ###
