"""long message ids, one open lead

Revision ID: 0dd1fc0742c5
Revises: c8c8555e0db4
Create Date: 2026-09-23 03:49:20.794544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd1fc0742c5'
down_revision: Union[str, Sequence[str], None] = 'c8c8555e0db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead_messages', 'external_message_id',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('uq_leads_open_per_person', 'leads', ['channel', 'external_id'], unique=True, postgresql_where=sa.text("status NOT IN ('enrolled', 'lost')"), sqlite_where=sa.text("status NOT IN ('enrolled', 'lost')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_leads_open_per_person', table_name='leads', postgresql_where=sa.text("status NOT IN ('enrolled', 'lost')"), sqlite_where=sa.text("status NOT IN ('enrolled', 'lost')"))
    op.alter_column('lead_messages', 'external_message_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
