"""customer profiles

Additive only (SPEC §13): one table with the account profile of each customer
per channel (Telegram user data, Instagram User Profile API). Existing tables
are untouched; profiles fill in as people write again.

Revision ID: 09e5f6abd1dc
Revises: e1dc9dcb77d3
Create Date: 2026-09-26 15:56:09.240626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09e5f6abd1dc'
down_revision: Union[str, Sequence[str], None] = 'e1dc9dcb77d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profiles',
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'external_id', name='uq_customer_profiles_channel_external')
    )
    op.create_index(op.f('ix_customer_profiles_created_at'), 'customer_profiles', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_profiles_created_at'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    # ### end Alembic commands ###
