"""forms

Additive only (SPEC §15): `forms` (Google-Forms-like pages), `form_submissions`
(answers, label snapshot, utm) and `leads.form_id` (the form that brought a lead,
channel "form"). Existing rows are untouched.

Revision ID: 3271adcbefbb
Revises: b597d8612c25
Create Date: 2026-09-26 21:28:18.296804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3271adcbefbb'
down_revision: Union[str, Sequence[str], None] = 'b597d8612c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('submit_label', sa.String(length=60), server_default='Yuborish', nullable=False),
    sa.Column('success_message', sa.Text(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_forms_created_at'), 'forms', ['created_at'], unique=False)
    op.create_table('form_submissions',
    sa.Column('form_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('answers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('utm', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submissions_created_at'), 'form_submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_form_submissions_form_id'), 'form_submissions', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_lead_id'), 'form_submissions', ['lead_id'], unique=False)
    op.add_column('leads', sa.Column('form_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_leads_form_id'), 'leads', ['form_id'], unique=False)
    op.create_foreign_key('fk_leads_form_id', 'leads', 'forms', ['form_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_leads_form_id', 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_form_id'), table_name='leads')
    op.drop_column('leads', 'form_id')
    op.drop_index(op.f('ix_form_submissions_lead_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_form_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_created_at'), table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index(op.f('ix_forms_created_at'), table_name='forms')
    op.drop_table('forms')
    # ### end Alembic commands ###
