"""data deletion requests

Additive only (SPEC §12.2, Meta App Review): one table recording each user data
deletion request received from Meta's signed data-deletion callback, with the
confirmation code shown on the public /data-deletion status page.

Revision ID: e1dc9dcb77d3
Revises: cc521603ff79
Create Date: 2026-09-26 10:51:09.050969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1dc9dcb77d3'
down_revision: Union[str, Sequence[str], None] = 'cc521603ff79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_deletion_requests',
    sa.Column('confirmation_code', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_user_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_code')
    )
    op.create_index(op.f('ix_data_deletion_requests_external_user_id'), 'data_deletion_requests', ['external_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_deletion_requests_external_user_id'), table_name='data_deletion_requests')
    op.drop_table('data_deletion_requests')
    # ### end Alembic commands ###
